#!/usr/bin/expect -f
set timeout 120
set pass "@qLVTyL|J5"

puts "===> Uploading deployment zip to Hostinger Staging..."
spawn scp -P 65002 -o StrictHostKeyChecking=no avinya-care-hostinger-deployment.zip u382139760@82.112.239.95:domains/test.avinyacarefoundation.org/public_html/
expect {
    "password:" {
        send "$pass\r"
    }
}
expect eof

puts "===> Uploading deployment zip to Hostinger Production..."
spawn scp -P 65002 -o StrictHostKeyChecking=no avinya-care-hostinger-deployment.zip u382139760@82.112.239.95:domains/avinyacarefoundation.org/public_html/
expect {
    "password:" {
        send "$pass\r"
    }
}
expect eof

puts "===> Unpacking and configuring Staging & Production environments..."
spawn ssh -p 65002 -o StrictHostKeyChecking=no u382139760@82.112.239.95 "cd domains/test.avinyacarefoundation.org/public_html && unzip -o avinya-care-hostinger-deployment.zip && cp -f .env.staging .env && rm -f avinya-care-hostinger-deployment.zip && cd ~/domains/avinyacarefoundation.org/public_html && unzip -o avinya-care-hostinger-deployment.zip && cp -f .env.production .env && rm -f avinya-care-hostinger-deployment.zip && echo DEPLOYMENT_COMPLETE"
expect {
    "password:" {
        send "$pass\r"
    }
}
expect eof
