import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const root = join(__dirname, '..');

const seedGalleries = [
  {
    id: "gal-01",
    gallery_id: "gal-01",
    title: "Mobile Medical Clinic Launch in Rural Palghar",
    slug: "mobile-medical-clinic-palghar",
    short_description: "Deploying state-of-the-art mobile diagnostic units equipped with digital X-ray and tele-pathology for remote villages.",
    description: "Our team launched two fully equipped mobile health vans servicing 14 tribal hamlets in Palghar district. Each unit provides free physician consultations, basic blood diagnostics, instant ECGs, and prescription distribution to underprivileged families who previously had to travel over 40 kilometers for basic medical care.",
    image: "https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Avinya Care Mobile Medical Van serving rural patients in Palghar",
    category: "Healthcare",
    event_date: "2026-02-15",
    location: "Palghar, Maharashtra",
    photographer: "Avinya Media Team",
    external_link: "https://avinyacarefoundation.org",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 1,
    created_at: "2026-02-16T10:00:00Z"
  },
  {
    id: "gal-02",
    gallery_id: "gal-02",
    title: "Pediatric Oncology Ward Art & Hope Workshop",
    slug: "pediatric-oncology-art-workshop",
    short_description: "Bringing smiles, creative therapy, and joyful interactive play sessions to young cancer warriors.",
    description: "Volunteers and pediatric care specialists spent a heartwarming afternoon with children undergoing cancer therapy. The art therapy session helps reduce stress, boost emotional health, and build resilience among young cancer patients.",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Children participating in therapeutic art workshop at hospital ward",
    category: "Events",
    event_date: "2026-01-28",
    location: "Mumbai, India",
    photographer: "Sneha Kulkarni",
    external_link: "",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 2,
    created_at: "2026-01-29T14:30:00Z"
  },
  {
    id: "gal-03",
    gallery_id: "gal-03",
    title: "Breast Cancer Early Detection Drive",
    slug: "breast-cancer-early-detection-drive",
    short_description: "Clinical examination and non-invasive screening for women in urban hamlets.",
    description: "Medical practitioners provided free breast examinations and thermal imaging screening for women in underserved pockets, enabling early identification of malignant nodules.",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Medical practitioner performing non-invasive health screening",
    category: "Awareness",
    event_date: "2026-03-05",
    location: "Thane, Maharashtra",
    photographer: "Rajesh Mehta",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 3,
    created_at: "2026-03-05T09:15:00Z"
  },
  {
    id: "gal-04",
    gallery_id: "gal-04",
    title: "Free Community Mammography & Mammogram Camp",
    slug: "free-community-mammography-camp",
    short_description: "Screened over 350 women in low-income urban settlements for early-stage breast abnormalities.",
    description: "In partnership with leading oncologists and diagnostic labs, Avinya Care conducted a comprehensive 3-day breast cancer screening camp. Participants received mammograms, thermal screening, and detailed nutritional counselling free of cost.",
    image: "https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Doctor explaining screening procedure to female patient",
    category: "Campaigns",
    event_date: "2026-02-04",
    location: "Dharavi, Mumbai",
    photographer: "Avinya Care Outreach",
    external_link: "https://avinyacarefoundation.org",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 4,
    created_at: "2026-02-05T11:20:00Z"
  },
  {
    id: "gal-05",
    gallery_id: "gal-05",
    title: "Voluntary Blood Donation Marathon",
    slug: "blood-donation-marathon",
    short_description: "Mobilizing grassroots blood donors for emergency surgeries and oncology transfusions.",
    description: "Over 450 units of blood were collected in a single day drive to maintain crucial stocks for civic hospital oncology wards and emergency trauma units across Mumbai.",
    image: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Voluntary blood donation drive organized by Avinya Care",
    category: "Community",
    event_date: "2026-01-12",
    location: "Navi Mumbai",
    photographer: "Vikram Desai",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 5,
    created_at: "2026-01-12T16:00:00Z"
  },
  {
    id: "gal-06",
    gallery_id: "gal-06",
    title: "Oncology Nursing & Caregiver Training Program",
    slug: "oncology-nursing-caregiver-training",
    short_description: "Empowering 120 community healthcare workers with specialized palliative and hospice care skills.",
    description: "Training grassroots healthcare workers in palliative care management, pain management protocols, hygiene support, and compassionate family counseling for advanced-stage cancer patients.",
    image: "https://images.unsplash.com/photo-1581056771107-24ca5f033842?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Healthcare professionals engaged in interactive medical workshop",
    category: "Healthcare",
    event_date: "2025-12-18",
    location: "Pune, Maharashtra",
    photographer: "Ananya Roy",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 6,
    created_at: "2025-12-19T08:30:00Z"
  },
  {
    id: "gal-07",
    gallery_id: "gal-07",
    title: "Cervical Cancer Awareness Rally & Walkathon",
    slug: "cervical-cancer-awareness-rally",
    short_description: "Spreading vital information about HPV vaccination and pap smear routines.",
    description: "Community health workers and student volunteers paraded through high-footfall corridors educating women on HPV immunizations and routine cervical screenings.",
    image: "https://images.unsplash.com/photo-1532938911079-1b06ac7ceec7?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Community health workers raising awareness with informational banners",
    category: "Awareness",
    event_date: "2026-01-05",
    location: "Nashik, Maharashtra",
    photographer: "Avinya Outreach Team",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 7,
    created_at: "2026-01-05T12:00:00Z"
  },
  {
    id: "gal-08",
    gallery_id: "gal-08",
    title: "Chemotherapy Care Kit Distribution Drive",
    slug: "chemotherapy-care-kit-distribution",
    short_description: "Distributing 500+ customized comfort packages containing oral care kits, anti-nausea supplies, and warm blankets.",
    description: "Patients undergoing intensive chemotherapy often face severe physical side effects. Our foundation partnered with civic hospitals to hand deliver essential care packages designed by oncology nurses to ease treatment recovery.",
    image: "https://images.unsplash.com/photo-1582750433449-648ed127bb54?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Volunteer handing over medical relief care package to patient family",
    category: "Community",
    event_date: "2025-11-20",
    location: "Mumbai, India",
    photographer: "Rohit Verma",
    external_link: "",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 8,
    created_at: "2025-11-21T15:45:00Z"
  },
  {
    id: "gal-09",
    gallery_id: "gal-09",
    title: "Subsidized Surgical Reconstruction Camp",
    slug: "surgical-camp-reconstruction",
    short_description: "Subsidized reconstructive procedures for post-mastectomy cancer survivors.",
    description: "Partnering with specialized reconstructive surgeons to provide subsidized procedures and post-operative recovery support for underprivileged breast cancer survivors.",
    image: "https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Surgeons operating in sterile hospital environment during subsidized camp",
    category: "Healthcare",
    event_date: "2025-10-14",
    location: "Aurangabad, Maharashtra",
    photographer: "Dr. S. Patil",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 9,
    created_at: "2025-10-15T10:00:00Z"
  },
  {
    id: "gal-10",
    gallery_id: "gal-10",
    title: "National Cancer Survivors' Day Celebration",
    slug: "national-cancer-survivors-day",
    short_description: "Honoring the courage and inspirational journeys of over 200 cancer survivors and their families.",
    description: "An uplifting evening filled with personal triumph stories, musical performances, and expert guidance on post-treatment wellness and recurrence prevention.",
    image: "https://images.unsplash.com/photo-1511632765486-a01980e01a18?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Cancer survivors celebrating victory and sharing hope together",
    category: "Events",
    event_date: "2025-11-08",
    location: "Mumbai, India",
    photographer: "Avinya Events",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 10,
    created_at: "2025-11-09T18:20:00Z"
  },
  {
    id: "gal-11",
    gallery_id: "gal-11",
    title: "Telemedicine Digital Kiosk Inauguration",
    slug: "telemedicine-kiosk-inauguration",
    short_description: "Bridging the urban-rural specialist gap through remote digital consultations.",
    description: "Patients in remote Ratnagiri villages can now consult leading oncologists in Mumbai via high-definition digital kiosks, receiving instant diagnostic evaluations without arduous travel.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Patient connecting with specialist doctor via high-speed digital telemedicine console",
    category: "Healthcare",
    event_date: "2025-09-30",
    location: "Ratnagiri, Maharashtra",
    photographer: "Tech Health Media",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 11,
    created_at: "2025-09-30T13:10:00Z"
  },
  {
    id: "gal-12",
    gallery_id: "gal-12",
    title: "Youth Tobacco & Anti-Smoking School Campaign",
    slug: "youth-tobacco-prevention-campaign",
    short_description: "Reaching 5,000+ students across 25 secondary schools to prevent early nicotine addiction.",
    description: "Interactive workshops using augmented reality models showing lung health impact, educating teenagers on oral cancer risks associated with gutkha and electronic cigarettes.",
    image: "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Students actively engaging during cancer prevention awareness lecture",
    category: "Campaigns",
    event_date: "2025-09-12",
    location: "Thane & Navi Mumbai",
    photographer: "Karan Sharma",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 12,
    created_at: "2025-09-13T09:40:00Z"
  },
  {
    id: "gal-13",
    gallery_id: "gal-13",
    title: "Rural Vision & Cataract Screening Medical Drive",
    slug: "rural-vision-cataract-screening",
    short_description: "Free comprehensive eye checkups and surgical referrals for senior citizens.",
    description: "Our ophthalmology team screened over 600 elderly villagers in Vasai-Virar, distributing free prescription glasses and scheduling 85 free cataract surgeries.",
    image: "https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Ophthalmologist checking patient vision with specialized diagnostic device",
    category: "Healthcare",
    event_date: "2026-02-20",
    location: "Vasai-Virar, Maharashtra",
    photographer: "Avinya Vision Wing",
    external_link: "",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 13,
    created_at: "2026-02-21T11:00:00Z"
  },
  {
    id: "gal-14",
    gallery_id: "gal-14",
    title: "Women's Wellness & Nutritional Health Seminar",
    slug: "womens-wellness-nutritional-health",
    short_description: "Educating mothers on preventative healthcare, anemia, and balanced diets.",
    description: "Interactive seminar empowering over 250 local mothers with practical knowledge on combating nutritional deficiencies, early warning signs of lifestyle diseases, and family health.",
    image: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Female health educator speaking during interactive community seminar",
    category: "Awareness",
    event_date: "2026-03-08",
    location: "Virar West, Mumbai",
    photographer: "Pooja Hegde",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 14,
    created_at: "2026-03-08T16:30:00Z"
  },
  {
    id: "gal-15",
    gallery_id: "gal-15",
    title: "Emergency Medical Relief Support Drive",
    slug: "emergency-medical-relief-support",
    short_description: "Rapid delivery of essential medical supplies and oxygen concentrators to civic hospitals.",
    description: "During critical healthcare surges, Avinya Care mobilized emergency medical supplies, sterile gowns, and oxygen support units to municipal healthcare centers.",
    image: "https://images.unsplash.com/photo-1505751172876-fa1923c5c528?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Medical supply boxes ready for urgent community distribution",
    category: "Community",
    event_date: "2025-08-14",
    location: "Mumbai & Thane",
    photographer: "Avinya Logistics Team",
    external_link: "",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 15,
    created_at: "2025-08-15T09:00:00Z"
  },
  {
    id: "gal-16",
    gallery_id: "gal-16",
    title: "Pediatric Immunization & Malnutrition Health Camp",
    slug: "pediatric-immunization-malnutrition-camp",
    short_description: "Providing essential vaccines and vitamin supplements to over 400 toddlers.",
    description: "A comprehensive pediatric health drive focused on early childhood immunizations, growth monitoring, and distributing fortified nutritional supplements to young infants.",
    image: "https://images.unsplash.com/photo-1584467735871-8e85353a8413?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Pediatric nurse examining infant patient with loving care",
    category: "Healthcare",
    event_date: "2025-09-02",
    location: "Bhiwandi, Maharashtra",
    photographer: "Siddharth Rao",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 16,
    created_at: "2025-09-03T10:15:00Z"
  },
  {
    id: "gal-17",
    gallery_id: "gal-17",
    title: "World Cancer Day Community Awareness Flash Mob",
    slug: "world-cancer-day-flash-mob",
    short_description: "Youth volunteers captivating public transit hubs to promote early screening.",
    description: "Dozens of energetic youth volunteers performed choreographed awareness acts at major railway terminals, distributing informational brochures on cancer prevention to thousands of commuters.",
    image: "https://images.unsplash.com/photo-1529156069898-49953e39b3ac?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Youth volunteers posing together during World Cancer Day event",
    category: "Events",
    event_date: "2026-02-04",
    location: "Andheri Station, Mumbai",
    photographer: "Avinya Youth Wing",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 17,
    created_at: "2026-02-04T18:00:00Z"
  },
  {
    id: "gal-18",
    gallery_id: "gal-18",
    title: "Free Diabetes & Hypertension Diagnostic Camp",
    slug: "diabetes-hypertension-diagnostic-camp",
    short_description: "Preventative screening for metabolic and cardiovascular conditions in senior citizens.",
    description: "Screened over 500 residents for elevated blood glucose and arterial hypertension, offering personalized dietary blueprints and free prescription starters.",
    image: "https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Nurse measuring blood pressure for senior citizen patient",
    category: "Campaigns",
    event_date: "2025-10-28",
    location: "Borivali, Mumbai",
    photographer: "Meera Nair",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 18,
    created_at: "2025-10-29T08:45:00Z"
  },
  {
    id: "gal-19",
    gallery_id: "gal-19",
    title: "Hospice Caregiver Support Group Gathering",
    slug: "hospice-caregiver-support-group",
    short_description: "A safe space for family caregivers of advanced cancer patients to share experiences.",
    description: "Facilitated by clinical psychologists and palliative counselors, this monthly circle provides emotional solace, coping techniques, and peer support to family members.",
    image: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Support group meeting with compassionate discussion circle",
    category: "Community",
    event_date: "2025-11-15",
    location: "Thane West, Maharashtra",
    photographer: "Avinya Care Counseling Unit",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 19,
    created_at: "2025-11-16T14:00:00Z"
  },
  {
    id: "gal-20",
    gallery_id: "gal-20",
    title: "Geriatric Health & Free Eye Care Mission",
    slug: "geriatric-health-eye-care-mission",
    short_description: "Specialized geriatric evaluations, mobility aids, and vision consultations for senior citizens.",
    description: "Dedicated full-day health pavilion providing elderly citizens with free joint care evaluations, hearing checkups, walking frames, and corrective eyewear.",
    image: "https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Senior citizen undergoing comfortable medical consultation with caring doctor",
    category: "Healthcare",
    event_date: "2026-01-20",
    location: "Kalyan, Maharashtra",
    photographer: "Deepak Joshi",
    external_link: "",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 20,
    created_at: "2026-01-21T10:30:00Z"
  },
  {
    id: "gal-21",
    gallery_id: "gal-21",
    title: "Oral Cancer Early Screening Drive in Industrial Belt",
    slug: "oral-cancer-screening-industrial-belt",
    short_description: "Screening 800+ factory workers for precancerous oral lesions and tobacco damage.",
    description: "Dental oncologists conducted targeted oral cavity examinations across industrial manufacturing hubs, identifying early mucosal changes and offering cessation therapy.",
    image: "https://images.unsplash.com/photo-1606811841689-23dfddce3e95?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Dentist inspecting oral cavity of factory worker during screening camp",
    category: "Awareness",
    event_date: "2025-08-25",
    location: "Taloja Industrial Area, Navi Mumbai",
    photographer: "Dr. A. Shah",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 21,
    created_at: "2025-08-26T12:00:00Z"
  },
  {
    id: "gal-22",
    gallery_id: "gal-22",
    title: "Clean Water & Hygiene Distribution Initiative",
    slug: "clean-water-hygiene-distribution",
    short_description: "Distributing water filtration kits and hygiene hampers to slum households.",
    description: "Preventing water-borne infections by distributing ceramic bio-water filters, antiseptic soaps, and feminine hygiene kits to 600 vulnerable families.",
    image: "https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Volunteers handing out hygiene supplies and water filters to families",
    category: "Community",
    event_date: "2025-07-18",
    location: "Malad East, Mumbai",
    photographer: "Avinya Relief Crew",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 22,
    created_at: "2025-07-19T11:45:00Z"
  },
  {
    id: "gal-23",
    gallery_id: "gal-23",
    title: "Cardiology Consultation & Free ECG Screening Day",
    slug: "cardiology-consultation-ecg-day",
    short_description: "Early cardiac risk assessment with instant 12-lead ECG diagnostics.",
    description: "Cardiologists provided free consultations and immediate 12-lead ECG evaluations to identify silent ischemic heart disease and arrhythmias in high-risk individuals.",
    image: "https://images.unsplash.com/photo-1629909613654-28e377c37b09?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Cardiologist evaluating digital ECG readout with patient",
    category: "Healthcare",
    event_date: "2025-12-05",
    location: "Vashi, Navi Mumbai",
    photographer: "Dr. K. Merchant",
    external_link: "",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 23,
    created_at: "2025-12-06T09:30:00Z"
  },
  {
    id: "gal-24",
    gallery_id: "gal-24",
    title: "Mental Health & Stress Resilience Workshop for Caregivers",
    slug: "mental-health-caregiver-resilience-workshop",
    short_description: "Guided mindfulness and psychological burn-out prevention for healthcare workers.",
    description: "Empowering frontline nurses and family caregivers with stress management tools, guided meditation sessions, and trauma recovery strategies.",
    image: "https://images.unsplash.com/photo-1506126613408-eca07ce68773?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Caregivers engaging in peaceful mindfulness and yoga session",
    category: "Events",
    event_date: "2025-10-10",
    location: "Mumbai, India",
    photographer: "Rohan Malhotra",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 24,
    created_at: "2025-10-11T15:20:00Z"
  },
  {
    id: "gal-25",
    gallery_id: "gal-25",
    title: "Mobile Mammography Van Outreach in Slum Clusters",
    slug: "mobile-mammography-van-slum-outreach",
    short_description: "Bringing high-tech digital mammography directly to women's doorsteps.",
    description: "Our mobile mammography unit navigated narrow urban settlements to provide private, dignified breast cancer diagnostic screenings for women unable to visit central hospitals.",
    image: "https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Mobile diagnostic medical bus parked near community screening hub",
    category: "Campaigns",
    event_date: "2026-01-15",
    location: "Kurla West, Mumbai",
    photographer: "Avinya Mobile Fleet",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 25,
    created_at: "2026-01-16T11:10:00Z"
  },
  {
    id: "gal-26",
    gallery_id: "gal-26",
    title: "Rehabilitative Care & Prosthetics Distribution Camp",
    slug: "rehabilitative-care-prosthetics-camp",
    short_description: "Restoring mobility and dignity for limb amputees and surgical survivors.",
    description: "Custom fitting and free distribution of lightweight artificial limbs, orthotic braces, and mobility devices to empower individuals to reclaim independent lives.",
    image: "https://images.unsplash.com/photo-1576765608535-5f04d1e3f289?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Physiotherapist assisting patient during mobility rehabilitation",
    category: "Healthcare",
    event_date: "2025-11-25",
    location: "Panvel, Maharashtra",
    photographer: "Sanjay Singhania",
    external_link: "",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 26,
    created_at: "2025-11-26T16:00:00Z"
  },
  {
    id: "gal-27",
    gallery_id: "gal-27",
    title: "Tobacco Cessation Counselling Kiosk Setup",
    slug: "tobacco-cessation-counselling-kiosk",
    short_description: "One-on-one addiction counseling and nicotine replacement therapy support.",
    description: "Setting up accessible kiosks at public transit stops offering free behavioral counseling, carbon monoxide breath tests, and nicotine patches to help citizens quit smoking.",
    image: "https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Counselor discussing addiction recovery steps with citizen",
    category: "Awareness",
    event_date: "2025-09-22",
    location: "Dadar, Mumbai",
    photographer: "Avinya Wellness Team",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 27,
    created_at: "2025-09-23T10:00:00Z"
  },
  {
    id: "gal-28",
    gallery_id: "gal-28",
    title: "Blood Platelet Donation Drive for Leukaemia Patients",
    slug: "platelet-donation-drive-leukaemia",
    short_description: "Single Donor Platelet (SDP) apheresis mobilization for pediatric cancer warriors.",
    description: "Specialized apheresis drive recruiting compatible SDP donors to supply life-saving platelet transfusions for pediatric bone marrow transplant and leukaemia patients.",
    image: "https://images.unsplash.com/photo-1615461066841-6116e61058f4?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Platelet donation machine during active apheresis collection procedure",
    category: "Community",
    event_date: "2026-02-10",
    location: "TMC Hospital, Mumbai",
    photographer: "Priya Saxena",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 28,
    created_at: "2026-02-11T13:45:00Z"
  },
  {
    id: "gal-29",
    gallery_id: "gal-29",
    title: "Diagnostic Pathology Camp for Tribal Villages",
    slug: "diagnostic-pathology-camp-tribal-villages",
    short_description: "On-site blood profiling, lipid panels, and liver function testing for remote communities.",
    description: "Deploying portable centrifuge units and automated bio-analyzers directly into tribal settlements to deliver instant blood work diagnostic reports.",
    image: "https://images.unsplash.com/photo-1579154204601-01588f351e67?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Pathologist analyzing blood samples with modern micro-centrifuge",
    category: "Healthcare",
    event_date: "2025-12-12",
    location: "Jawhar, Palghar",
    photographer: "Avinya Lab Wing",
    external_link: "",
    has_details: true,
    is_featured: false,
    is_published: true,
    sort_order: 29,
    created_at: "2025-12-13T09:15:00Z"
  },
  {
    id: "gal-30",
    gallery_id: "gal-30",
    title: "Annual Hope Gala & Benefactor Recognition Night",
    slug: "annual-hope-gala-benefactor-night",
    short_description: "Celebrating donors, medical partners, and volunteers who powered our year of impact.",
    description: "An inspiring evening honoring key medical advisors, corporate CSR partners, and grassroot volunteers whose generosity funded treatment for over 1,200 cancer patients.",
    image: "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&w=1200&q=80",
    alt_text: "Stage illumination during Avinya Foundation Annual Hope Gala night",
    category: "Events",
    event_date: "2025-12-28",
    location: "Taj Lands End, Mumbai",
    photographer: "Avinya Gala Media",
    external_link: "",
    has_details: true,
    is_featured: true,
    is_published: true,
    sort_order: 30,
    created_at: "2025-12-29T21:00:00Z"
  }
];

async function run() {
  const seedPath = join(root, 'data', 'seed_galleries.json');
  await writeFile(seedPath, JSON.stringify(seedGalleries, null, 2), 'utf-8');
  console.log(`Successfully wrote ${seedGalleries.length} items to data/seed_galleries.json`);

  const dbPath = join(root, 'cache', 'healthcare_db.json');
  try {
    const raw = await readFile(dbPath, 'utf-8');
    const db = JSON.parse(raw);
    db.galleries = seedGalleries;
    db.lastUpdated = new Date().toISOString();
    await writeFile(dbPath, JSON.stringify(db, null, 2), 'utf-8');
    console.log(`Successfully updated cache/healthcare_db.json with ${seedGalleries.length} gallery items.`);
  } catch (e) {
    console.warn('cache/healthcare_db.json not found or error updating:', e.message);
  }
}

run();
